### ISSUE TITLE
AGH_MSD_v2.zip is not available anymore.

### ISSUE THREAD

**Issue by a4pasu** [michalkoziarski/MarineSnowCNN#1]
I'm interested in reproduce the algorithm behavior but found that AGH_MSD_v2.zip is not available anymore. Can you re-upload it?
  
https://www.dropbox.com/s/nlowvsi0nnd4xrh/AGH_MSD_v2.zip?dl=0

**Comment by michalkoziarski** [comment]
I reuploaded whole supplementary material, please check out the readme and let me know if you have any problems.

**Comment by a4pasu** [comment]
Thank you.
